kind: configuration
pipelines:
  bilby:
    sampler:
      sampler: nessai
    scheduler:
      accounting group: ligo.dev.o4.cbc.pe.bilby
      request cpus: 4
  bayeswave:
    scheduler:
      accounting group: ligo.dev.o4.cbc.pe.lalinference
      request memory: 1024
      request post memory: 16384
