kind: configuration
pipelines:
  bilby:
    sampler:
      sampler: dynesty
      parallel jobs: 2
      sampler kwargs: "{nlive: 100, dlogz: 1, nact: 5}"
    scheduler:
      accounting group: ligo.dev.o4.cbc.pe.bilby
      request cpus: 16
  bayeswave:
    likelihood:
      iterations: 250000
    scheduler:
      accounting group: ligo.dev.o4.cbc.pe.bilby
      request memory: 1024
      request post memory: 16384
postprocessing:
  pesummary:
    accounting group: ligo.dev.o4.cbc.pe.bilby
    cosmology: Planck15_lal
    evolve spins: forward
    multiprocess: 4
    redshift: exact
    regenerate posteriors:
    - redshift
    - mass_1_source
    - mass_2_source
    - chirp_mass_source
    - total_mass_source
    - final_mass_source
    - final_mass_source_non_evolved
    - radiated_energy
    skymap samples: 2000
