kind: configuration
data:
  channels:
    H1: H1:GDS-CALIB_STRAIN_INJ1_O3Replay
    L1: L1:GDS-CALIB_STRAIN_INJ1_O3Replay
    V1: V1:Hrec_hoft_16384Hz_O3Replay
  frame types:
    H1: H1_O3ReplayMDC_llhoft
    L1: L1_O3ReplayMDC_llhoft
    V1: V1_O3E2ERep1_llhoft
pipelines:
  bilby:
    quality:
      state vector:
        L1: L1:DCS-CALIB_STATE_VECTOR_C01
        H1: H1:DCS-CALIB_STATE_VECTOR_C01
        V1: V1:DQ_ANALYSIS_STATE_VECTOR
    sampler:
      sampler: dynesty
      parallel jobs: 2
      sampler kwargs: "{nlive: 100, dlogz: 1}"
    scheduler:
      local generation: True
      osg: True
      accounting group: ligo.dev.o4.cbc.pe.bilby
      request cpus: 16
  bayeswave:
    quality:
      state vector:
        L1: L1:DCS-CALIB_STATE_VECTOR_C01
        H1: H1:DCS-CALIB_STATE_VECTOR_C01
        V1: V1:DQ_ANALYSIS_STATE_VECTOR
    likelihood:
      iterations: 250000
    scheduler:
      accounting group: ligo.dev.o4.cbc.pe.bilby
      copy frames: True
      request memory: 1024
      request post memory: 16384
      osg: True
postprocessing:
  pesummary:
    accounting group: ligo.dev.o4.cbc.pe.bilby
    cosmology: Planck15_lal
    evolve spins: forward
    multiprocess: 4
    redshift: exact
    regenerate posteriors:
    - redshift
    - mass_1_source
    - mass_2_source
    - chirp_mass_source
    - total_mass_source
    - final_mass_source
    - final_mass_source_non_evolved
    - radiated_energy
    skymap samples: 2000
